article/urls.py
from django.urls import path
from . import views
from django.urls import re_path

# 原则上一定要写这一行，否则html中会报错 'article' is not a registered namespace，
# 当然如果在MyBlog的urls.py中设置了就没有问题
app_name = 'article'
urlpatterns = [
    # 文章栏目
    path('article-column/', views.article_column, name="article_column"),
    # 修改文章栏目
    path('rename-article-column/', views.rename_article_column, name="rename_article_column"),
    # 删除文章栏目
    path('del-article-column/', views.del_article_column, name="del_article_column"),
    # 发表文章
    path('article-post/', views.article_post, name="article_post"),
    # 文章列表
    path('article-list/', views.article_list, name="article_list"),
    # 查看文章（正则表达式匹配）
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    # 删除文章
    path('del-article/', views.del_article, name="del_article"),
    # 修改文章
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    # 前台展示文章列表
    path('list-article-titles/', views.article_titles, name="article_titles"),
    # 前台展示具体文章信息
    path('article-content/<int:id>/<slug:slug>/', views.article_detail, name="article_content"),
    # 显示某一作者的全部文章信息
    path('list-article-titles/<username>/', views.article_titles, name="author_articles"),
    # 点赞文章
    path('like-article/', views.like_article, name="like_article"),
    # 文章标签
    path('article-tag/', views.article_tag, name="article_tag"),
    # 删除文章标签
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 如果不用自定义的方式指定模板位置，Django会在运行时自动去templates查找render()函数中所指定的模板文件。
    path(r'', views.blog_list, name='blog_list'),
    path(r'<int:article_id>/', views.blog_detail, name='blog_detail'),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # 进入聊天室
    path('', views.enter, name='enter'),
    # 聊天室界面，这样可以解析room_name，直接做字符串保持
    path('<str:room_name>/', views.room, name='room'),
    # 个人所有信息界面
    # path('contact/', views.contact, name='all_contact'),
    # 个人私聊界面
    path('contact/<str:user1_name>/<str:user2_name>', views.contact, name='contact'),
]

myblog2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新版django取消了默认namespace，一定要加namespace，这样html文件中才可以访问blog
    # 如果加上namespace，那么include前面的第一个参数需要改为二元组，第二个内容为app_name
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('image/', include(('image.urls', 'image'), namespace='image')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 添加允许访问media的url

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from slugify import slugify
from django.urls import reverse


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


# 文章标签
class ArticleTag(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tag")
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    # related_name = article，那么就可以通过user.article访问ArticlePost这个类
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)  # 用于生成友好的url，如空格换成-而不是%20
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    # 点赞功能，一篇文章可能多个用户喜欢，一个用户也可以喜欢多篇文章，所以是多对多
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    # 和文章标签对应起来（多对多）
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)
    views = models.IntegerField(blank=True, default=0)  # 浏览数

    class Meta:
        ordering = ("-updated",)  # 按照文章发布时间倒序排列
        # index_together = (('id', 'slug'),) 对数据库中的这两个字段建立索引，
        # 以后就可以通过每篇文章的id和slug来获取该文章对象了，这样建立索引以后，能提高读取文章对象的速度。
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    # save() 每个数据模型类都有一个save方法，在本类中对这个方法重写，
    # 是为了实现 self.slug = slugify(self.title)，然后再执行父类的save方法
    def save(self, *args, **kargs):
        self.slug = slugify(self.title)  # 友好化title字符串
        super(ArticlePost, self).save(*args, **kargs)

    # 获取某篇文章的url，使用reverse针对名称进行url绑定（需要登录）
    # 因为它使用了views.py中的article_detail方法，我们于此加了一个修饰器，login_required
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    # 获取某篇文章的url，使用reverse针对名称进行url绑定（不需要登录）
    def get_url_path(self):
        return reverse("article:article_content", args=[self.id, self.slug])


# 评论
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")  # 一篇文章多篇评论
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")  # 对用户而言，只需要上传标题和文章内容


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
import json
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from article.forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm, CommentForm
from .models import ArticleColumn, ArticlePost, ArticleTag


@login_required(login_url='/account/login/')
@csrf_exempt  # 一种django的加密机制，减少csrf攻击
def article_column(request):
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user=request.user, column=column_name)  # 遍历检索是否有重复的栏目名
        if columns:
            return HttpResponse("该栏目名已存在！")
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("成功创建！")
    else:
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})


@login_required(login_url='/account/login')
@require_POST  # 修饰器，只能是POST访问
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("成功修改")
    except:
        return HttpResponse("失败")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("删除成功")
    except:
        return HttpResponse("删除失败")


# 发布文章
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)  # 此时还未上传到数据库
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']  # tags以json包形式传递
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("成功上传")
            except:
                return HttpResponse("表单有效，但上传失败")
        else:
            return HttpResponse("表单无效")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form,
                       "article_columns": article_columns, "article_tags": article_tags})  # 此处传参html中可以用到


# 展示文章列表
@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # django自带分页器，参数表示每页显示几条
    page = request.GET.get('page')
    try:  # 尝试获取当前页
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:  # 如果页面非整数，返回第一页
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:  # 如果遇见空页，则返回最后一页
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


# 展示具体文章
@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


# 删除具体文章
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("删除成功")
    except:
        return HttpResponse("删除失败")


# 修改文章
@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",
                      {"article": article, "article_columns": article_columns,
                       "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("修改成功")
        except:
            return HttpResponse("修改失败")


# 文章标签页面
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html",
                      {"article_tags": article_tags, "article_tag_form": article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("成功上传")
            except:
                return HttpResponse("保存发生异常")
        else:
            return HttpResponse("表单无效")


# 删除文章标签
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("成功删除")
    except:
        return HttpResponse("删除失败")


# 前台展示文章列表, 如果传进username则表示只展示某一作者的全部文章
def article_titles(request, username=None):
    if username:
        user = User.objects.get(username=username)
        articles_title = ArticlePost.objects.filter(author=user)
        try:  # 尝试获取用户详细资料
            userinfo = user.userinfo
        except:
            userinfo = None
    else:
        articles_title = ArticlePost.objects.all()  # 所有上传的博客
    paginator = Paginator(articles_title, 10)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    if username:
        return render(request, "article/list/author_articles.html",
                      {"articles": articles, "page": current_page, "userinfo": userinfo, "user": user})
    return render(request, "article/list/article_titles.html", {"articles": articles, "page": current_page})


# 前台文章具体信息
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    # total_views = r.incr("article:{}:views".format(article.id))
    # import redis
    # from django.conf import settings
    # 注：用redis统计文章访问量较快，大型网站常用。此处个人博客不用，省的每次开redis服务器
    # r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)
    # r.zincrby('article_ranking', 1, article.id)  # 每次访问时，自增article_ranking里对应article_id的分数

    # 按照索引范围获取name对应的有序集合的元素，0~-1表示从开头到结尾，排序规则desc=True表示从大到小
    # article_ranking = r.zrange("article_ranking", 0, -1, desc=True)[:10]
    # article_ranking_ids = [int(id) for id in article_ranking]  # 对字典而言，直接for的话取的是key

    # most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))  # id__in可以传进列表一次取值
    # most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))  # 用id排序

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()  # get方法的话，直接创建表单返回
        article.views += 1
        article.save(update_fields=['views'])  # 存进数据库

    most_viewed_articles = ArticlePost.objects.all().order_by('-views')[:4]  # 以views数量降序排序

    article_tags_ids = article.article_tag.values_list("id", flat=True)  # 得到当前对象(article_tag是一个对象）的指定字段值
    # exclude排除id相同的文章
    similar_articles = ArticlePost.objects.filter(article_tag__in=article_tags_ids).exclude(id=article.id)
    # 聚合，取4篇相似文章，依照最新和相同标签两种排序方式
    similar_articles = similar_articles.annotate(same_tags=Count("article_tag")).order_by('-same_tags', '-created')[:4]

    # return render(request, "article/list/article_content.html",
    # {"article": article, "total_views": total_views,

templates/article/list/article_content.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}文章内容{% endblock %}
{% block content %}
<!--计数的total_likes，count是自带的一种方法-->
{% with total_likes=article.users_like.count users_like=article.users_like.all %}
<div class="container">
    <div class="col-md-9">
        <header>
            <h1>{{ article.title }}</h1>
            <p>
                <a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                <span style="margin-left:20px">文章浏览次数：{{ total_views }}</span>
                <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up">共有{{ total_likes }}人点赞</span>
                <p> <span style="margin-right: 10px"><strong>Tags:</strong></span> {{ article.article_tag.all | join:", "}}</p>

            </p>
        </header>

        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
        <div id='editormd-view'>
            <textarea id="append-test" style="display:none;">{{ article.body }}</textarea>
        </div>
        <div>
            <p class="text-center">
                <a onclick="like_article({{article.id}}, 'like')" href="#">
                    <span class="glyphicon glyphicon-thumbs-up">点赞</span>
                </a>
                <a onclick="like_article({{article.id}}, 'unlike')" href="#">
                    <span style="margin-left: 15px;" class="glyphicon glyphicon-thumbs-down">取消点赞</span>
                </a>
            </p>
        </div>
        <div>
            <p class="text-center"><strong>点赞本文的读者</strong></p>
            {% for user in article.users_like.all %}
            <p class="text-center">{{user.username}}</p>
            {% empty %}
            <p class="text-center">还没有人对此文章表态</p>
            {% endfor %}
        </div>
        <div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>评论区</h3>
            {% for comment in article.comments.all %}
            <div>
                <p><strong>{{ comment.commentator }}</strong>评论说:</p>
                <p style="margin-left:40px;">{{ comment.body }}</p>
            </div>
            {% empty %}
            <p>这篇文章还没有评论</p>
            {% endfor %}

            <h3><span class="glyphicon glyphicon-send"></span>在此处留下您对本文的看法</h3>
            <form action="." method="post" class="form-horizontal" role="form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value="提交" class="btn btn-primary"></p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-3">
        <p class="text-center">
        <h3>最受欢迎文章</h3></p>
        <ol>
            {% for article_rank in most_viewed_articles %}
                <li><a href="{{article_rank.get_url_path}}">{{ article_rank.title }}</a></li>
            {% endfor %}
        </ol>

        <hr>
            <p class="text-center">
            <h3>最新文章</h3></p>
            {% latest_articles 4 %}

        <hr>
        <p class="text-center">
        <h3>最多评论文章</h3></p>
        {% most_commented_articles as most_comments %}
        <ul>
            {% for comment_article in most_comments %}
            <li>
                <a href="{{comment_article.get_url_path}}">{{ comment_article.title }}</a>
            </li>
            {% endfor %}
        </ul>
        <hr>

        <p class="text-center">
        <h3>推荐相似文章</h3></p>
        <ul>
            {% for similar in similar_articles %}
            <li>
                <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a></p>
            </li>
            {% empty %}
            <p>很抱歉，这篇文章目前还没有相似文章</p>
            {% endfor %}
        </ul>
    </div>
</div>

<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram : true,
    });
});
function like_article(id, action){
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e){
            if(e=="点赞成功"){
                alert("感谢您的点赞！");
                window.location.reload();   //刷新界面
            }else if(e == "点赞取消"){
                alert("我会继续努力");
                window.location.reload();
            }
            else{
                alert("请先登录")
            }
        },
    });
}

</script>
{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} articles {% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
    <p>这里已经有{% total_articles %}篇文章供你阅读</p> <!--这里是我们自定义的模板标签，返回ArticlePost.objects.count-->
</div>
<div class="container">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者:<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <!--slice:70表示从文章字符中取前70个展示，linebreakes表示原文的换行也继续产生效用-->
        <p class="list-group-item-text">概要:{{article.body|slice:'70'| linebreaks}}</p>
    </div>
    {% endfor %}
    {% include "paginator.html" %}
</div>
{% endblock %}

templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}用户文章列表{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
</div>
<div class="container">
    <div class="col-md-8">
        {% for article in articles %}
        <div class="list-group">
            <a href="{{article.get_url_path}}" class="list-group-item active">
                <h4 class="list-group-item-heading">{{article.title}}</h4>
            </a>
            <p class="list-group-item-text">作者:
                <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a>
            </p>
            <p class="list-group-item-text">概要:{{article.body|slice:'70'|linebreaks}} </p>
        </div>
        {% endfor %}
        {% include "paginator.html" %}
    </div>
    <div class="col-md-4">
        <div>
            {% if userinfo.photo %}     <!--如果存在用户详细资料，则展示。不要striptags也是可以的-->
            <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face" style="width: 300px">
            {% else %}
            <img name="user_face" src="{% static 'images/default_face.jpg' %}" class="img-circle" id="my_photo" style="width: 300px">
            {% endif %}
        </div>
        <div>
            <p>{{ user.username }}</p>
            <p>共发表{% author_total_articles user %}篇文章</p>
            {% if userinfo %}
            <p>{{ userinfo.company }}</p>
            <p>{{ userinfo.aboutme }}</p>
            {% else %}
            <p>这个作者并没有详细资料</p>
            {% endif %}
            <a href="{% url 'chat:contact' request.user.username user.username %}"><p>给该作者发消息</p></a>
        </div>
    </div>
</div>
{% endblock %}

templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>