article/urls.py
from django.urls import path
from . import views
from django.urls import re_path

# 原则上一定要写这一行，否则html中会报错 'article' is not a registered namespace，
# 当然如果在MyBlog的urls.py中设置了就没有问题
app_name = 'article'
urlpatterns = [
    # 文章栏目
    path('article-column/', views.article_column, name="article_column"),
    # 修改文章栏目
    path('rename-article-column/', views.rename_article_column, name="rename_article_column"),
    # 删除文章栏目
    path('del-article-column/', views.del_article_column, name="del_article_column"),
    # 发表文章
    path('article-post/', views.article_post, name="article_post"),
    # 文章列表
    path('article-list/', views.article_list, name="article_list"),
    # 查看文章（正则表达式匹配）
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    # 删除文章
    path('del-article/', views.del_article, name="del_article"),
    # 修改文章
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    # 前台展示文章列表
    path('list-article-titles/', views.article_titles, name="article_titles"),
    # 前台展示具体文章信息
    path('article-content/<int:id>/<slug:slug>/', views.article_detail, name="article_content"),
    # 显示某一作者的全部文章信息
    path('list-article-titles/<username>/', views.article_titles, name="author_articles"),
    # 点赞文章
    path('like-article/', views.like_article, name="like_article"),
    # 文章标签
    path('article-tag/', views.article_tag, name="article_tag"),
    # 删除文章标签
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 如果不用自定义的方式指定模板位置，Django会在运行时自动去templates查找render()函数中所指定的模板文件。
    path(r'', views.blog_list, name='blog_list'),
    path(r'<int:article_id>/', views.blog_detail, name='blog_detail'),
]

myblog2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新版django取消了默认namespace，一定要加namespace，这样html文件中才可以访问blog
    # 如果加上namespace，那么include前面的第一个参数需要改为二元组，第二个内容为app_name
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('image/', include(('image.urls', 'image'), namespace='image')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 添加允许访问media的url

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from slugify import slugify
from django.urls import reverse


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


# 文章标签
class ArticleTag(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tag")
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    # related_name = article，那么就可以通过user.article访问ArticlePost这个类
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)  # 用于生成友好的url，如空格换成-而不是%20
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    # 点赞功能，一篇文章可能多个用户喜欢，一个用户也可以喜欢多篇文章，所以是多对多
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    # 和文章标签对应起来（多对多）
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)
    views = models.IntegerField(blank=True, default=0)  # 浏览数

    class Meta:
        ordering = ("-updated",)  # 按照文章发布时间倒序排列
        # index_together = (('id', 'slug'),) 对数据库中的这两个字段建立索引，
        # 以后就可以通过每篇文章的id和slug来获取该文章对象了，这样建立索引以后，能提高读取文章对象的速度。
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    # save() 每个数据模型类都有一个save方法，在本类中对这个方法重写，
    # 是为了实现 self.slug = slugify(self.title)，然后再执行父类的save方法
    def save(self, *args, **kargs):
        self.slug = slugify(self.title)  # 友好化title字符串
        super(ArticlePost, self).save(*args, **kargs)

    # 获取某篇文章的url，使用reverse针对名称进行url绑定（需要登录）
    # 因为它使用了views.py中的article_detail方法，我们于此加了一个修饰器，login_required
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    # 获取某篇文章的url，使用reverse针对名称进行url绑定（不需要登录）
    def get_url_path(self):
        return reverse("article:article_content", args=[self.id, self.slug])


# 评论
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")  # 一篇文章多篇评论
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")  # 对用户而言，只需要上传标题和文章内容


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
import json
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from article.forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm, CommentForm
from .models import ArticleColumn, ArticlePost, ArticleTag


@login_required(login_url='/account/login/')
@csrf_exempt  # 一种django的加密机制，减少csrf攻击
def article_column(request):
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user=request.user, column=column_name)  # 遍历检索是否有重复的栏目名
        if columns:
            return HttpResponse("该栏目名已存在！")
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("成功创建！")
    else:
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})


@login_required(login_url='/account/login')
@require_POST  # 修饰器，只能是POST访问
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("成功修改")
    except:
        return HttpResponse("失败")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("删除成功")
    except:
        return HttpResponse("删除失败")


# 发布文章
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)  # 此时还未上传到数据库
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']  # tags以json包形式传递
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("成功上传")
            except:
                return HttpResponse("表单有效，但上传失败")
        else:
            return HttpResponse("表单无效")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form,
                       "article_columns": article_columns, "article_tags": article_tags})  # 此处传参html中可以用到


# 展示文章列表
@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # django自带分页器，参数表示每页显示几条
    page = request.GET.get('page')
    try:  # 尝试获取当前页
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:  # 如果页面非整数，返回第一页
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:  # 如果遇见空页，则返回最后一页
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


# 展示具体文章
@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


# 删除具体文章
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("删除成功")
    except:
        return HttpResponse("删除失败")


# 修改文章
@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",
                      {"article": article, "article_columns": article_columns,
                       "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("修改成功")
        except:
            return HttpResponse("修改失败")


# 文章标签页面
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html",
                      {"article_tags": article_tags, "article_tag_form": article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("成功上传")
            except:
                return HttpResponse("保存发生异常")
        else:
            return HttpResponse("表单无效")


# 删除文章标签
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("成功删除")
    except:
        return HttpResponse("删除失败")


# 前台展示文章列表, 如果传进username则表示只展示某一作者的全部文章
def article_titles(request, username=None):
    if username:
        user = User.objects.get(username=username)
        articles_title = ArticlePost.objects.filter(author=user)
        try:  # 尝试获取用户详细资料
            userinfo = user.userinfo
        except:
            userinfo = None
    else:
        articles_title = ArticlePost.objects.all()  # 所有上传的博客
    paginator = Paginator(articles_title, 10)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    if username:
        return render(request, "article/list/author_articles.html",
                      {"articles": articles, "page": current_page, "userinfo": userinfo, "user": user})
    return render(request, "article/list/article_titles.html", {"articles": articles, "page": current_page})


# 前台文章具体信息
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    # total_views = r.incr("article:{}:views".format(article.id))
    # import redis
    # from django.conf import settings
    # 注：用redis统计文章访问量较快，大型网站常用。此处个人博客不用，省的每次开redis服务器
    # r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)
    # r.zincrby('article_ranking', 1, article.id)  # 每次访问时，自增article_ranking里对应article_id的分数

    # 按照索引范围获取name对应的有序集合的元素，0~-1表示从开头到结尾，排序规则desc=True表示从大到小
    # article_ranking = r.zrange("article_ranking", 0, -1, desc=True)[:10]
    # article_ranking_ids = [int(id) for id in article_ranking]  # 对字典而言，直接for的话取的是key

    # most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))  # id__in可以传进列表一次取值
    # most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))  # 用id排序

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()  # get方法的话，直接创建表单返回
        article.views += 1
        article.save(update_fields=['views'])  # 存进数据库

    most_viewed_articles = ArticlePost.objects.all().order_by('-views')[:4]  # 以views数量降序排序

    article_tags_ids = article.article_tag.values_list("id", flat=True)  # 得到当前对象(article_tag是一个对象）的指定字段值
    # exclude排除id相同的文章
    similar_articles = ArticlePost.objects.filter(article_tag__in=article_tags_ids).exclude(id=article.id)
    # 聚合，取4篇相似文章，依照最新和相同标签两种排序方式
    similar_articles = similar_articles.annotate(same_tags=Count("article_tag")).order_by('-same_tags', '-created')[:4]

    # return render(request, "article/list/article_content.html",
    # {"article": article, "total_views": total_views,

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章栏目{% endblock %}
{% block content %}
<div>
    <p class="text-right">
        <!--<button class="btn btn-primary">添加文章</button>-->
        <button id="add_column" onclick="add_column()" class="btn btn-primary">添加栏目</button>
    </p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"><span class="glyphicon glyphicon-pencil"></span></a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% empty %}
        <p>您还没有设置任何栏目</p>
        {% endfor %}
    </table>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增文章栏目",
            content: '<div class="text-center" style="margin-top:20px"><p> 请输入新的栏目名称</p><p>{{ column_form.column }}</p></div>',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: { "column": column_name },
                    success: function (e) {
                        if (e == "成功创建！") {
                            parent.location.reload();
                            alert("成功创建！");
                        } else {
                            alert("此栏目名称已存在，请更换")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }

    function edit_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "编辑栏目",
            content: '<div class="text-center" style="margin-top:20px"> <p>新的栏目名称为：</p><p><input type="text" id="new_name" value="'+name+'"></p> </div>',
            btn:['确定', '取消'],
            yes: function(index, layero){
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name},
                    success: function(e){
                        if(e=="成功修改"){
                            parent.location.reload();
                            layer.msg("成功修改！");
                        }else{
                            layer.msg("很抱歉，修改失败。")
                        }
                    },
                });
            },
        });
    }

    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type:"POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="删除成功"){
                            parent.location.reload();
                            layer.msg("删除成功！");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>

{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}
{% block content %}
<div>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>
                <a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a nane="delete" href="javascript:" onclick="del_article(this, {{ article.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type:"POST",
                    data: {"article_id":article_id},
                    success: function(e){
                        if(e=="删除成功"){
                            parent.location.reload();
                            layer.msg("删除成功！");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }

</script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章栏目{% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">
        {% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div>  <!--用于输入文章标题-->
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %} <!--将所有栏目用选择的形式展现-->
                    <option value="{{column.id}}">{{column.column}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章标签:</span></div>
            <div class="col-md-10 text-left">
                {% for tag in article_tags %}
                <label class="checkbox-inline">     <!--bootstrap提供复选框-->
                    <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}"> {{ tag.tag }}
                </label>
                {% empty %}
                <p>您还没有设定文章标签，请<a href="{% url 'article:article_tag' %}">设置</a></p>
                {% endfor %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <!--<div class="col-md-10 text-left">{{article_post_form.body}}</div>   用于输入文章内容-->
            <div id="editormd" class="col-md-10 text-left">     <!--使用markdown输入文章内容-->
                <textarea style="display:none;" id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            syncScrolling : "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>

<script type="text/javascript">
function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    var article_tags = [];
    $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
    $.ajax({
        url: "{% url 'article:article_post' %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)}, //传入参数
        success: function(e){
            if(e=="成功上传"){
                //layer.msg("成功上传！");
                location.href = "{% url 'article:article_list' %}";//修改后：文章发布成功后跳转到文章列表
            }else if(e=="表单有效，但上传失败"){
                layer.msg("表单有效，但上传失败") ;
            }else{
                layer.msg("项目名称必须填写，不能为空。");
            }
        },
    });
}
</script>

{% endblock %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
    <div class="col-md-10">
        <div style="margin-left:10px">
            <form class="form-horizontal" action="." method="post">{% csrf_token %}
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>标题:</span></div>
                    <div class="col-md-10 text-left">{{this_article_form.title}}</div>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>栏目:</span></div>
                    <div class="col-md-10 text-left">
                        <select id="which_column">
                            {% for column in article_columns %}
                            {% if column == this_article_column.column %}
                            <option value="{{column.id}}" selected="selected">{{column.column}}</option>    <!--直接选上-->
                            {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>

                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>内容:</span></div>
                    <div id="editormd" class="col-md-10 text-left">
                        <!--{{article_post_form.body}}-->
                        <textarea style="display:none;" id="id_body">{{article.body}}</textarea>
                    </div>
                </div>
                <div class="row">
                    <input type="button" class="btn btn-primary btn-lg" value="修改" onclick="redit_article()">
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width : "100%",
        height : 640,
        //syncScrolling : "single",
        path : "{% static 'editor/lib/' %}",
    });
});

</script>

<script type="text/javascript">
function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:redit_article' article.id %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id},
        success: function(e){
            if(e=="修改成功"){
                layer.msg("修改成功！");
                location.href = "{% url 'article:article_list' %}";
            }else{
                layer.msg("抱歉，修改失败了.");
            }
        },
    });
}

</script>

{% endblock %}