account/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# app_name = 'account'  本来是一定要写这一行，否则html中会报错 'account' is not a registered namespace
# 但在MyBlog的urls.py中，已经将该app_name传入，所以不会遇到该问题

urlpatterns = [
    # path(r'login/', views.user_login, name='user_login'),
    # Django内置的登录方法 LoginView（）函数里有一个默认参数redirect_field_name=LOGIN_REDIRECT_URL，
    # 这就是登录后的重定向设置，我们需要到settings.py设置LOGIN_REDIRECT_URL，登录后重定向到/blog/
    path(r'login/', views.user_login, name='user_login'),
    # 使用Django内置的登出方法
    path(r'loginout/', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='user_logout'),
    # 图片验证码

    # ^表行开头，\d表数字，+表示至少有一个，$表行结尾，url有匹配正则表达式功能
    url(r'^verify_image/(\d+)/(\d+)/$', views.verify_image, name='verify_image'),
    # 注册
    path(r'register/', views.user_register, name='user_register'),

    # 修改密码
    path('password-change/',
         auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",
                                               success_url="/account/password-change-done/"),  # 成功修改则跳转到对应的url
         name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),
         name='password_change_done'),

    # 重置密码
    path('password-reset/',  # 重置界面
         auth_views.PasswordResetView.as_view(
             template_name="account/password_reset_form.html",
             email_template_name="account/password_reset_email.html",
             subject_template_name="account/password_reset_subject.txt",
             success_url="/account/password-reset-done/"),
         name='password_reset'),
    path('password-reset-done/',  # 填写完重置信息
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',  # 发送重置邮件，uid和token组成url
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",
                                                     success_url='/account/password-reset-complete/'),
         name="password_reset_confirm"),
    path('password-reset-complete/',  # 重置成功
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # 用户个人信息界面
    path('my-information/', views.myself, name='my_information'),
    # 用户个人信息编辑界面
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    # 用户上传图片
    path('my-image/', views.my_image, name="my_image"),


]

article/urls.py
from django.urls import path
from . import views
from django.urls import re_path

# 原则上一定要写这一行，否则html中会报错 'article' is not a registered namespace，
# 当然如果在MyBlog的urls.py中设置了就没有问题
app_name = 'article'
urlpatterns = [
    # 文章栏目
    path('article-column/', views.article_column, name="article_column"),
    # 修改文章栏目
    path('rename-article-column/', views.rename_article_column, name="rename_article_column"),
    # 删除文章栏目
    path('del-article-column/', views.del_article_column, name="del_article_column"),
    # 发表文章
    path('article-post/', views.article_post, name="article_post"),
    # 文章列表
    path('article-list/', views.article_list, name="article_list"),
    # 查看文章（正则表达式匹配）
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    # 删除文章
    path('del-article/', views.del_article, name="del_article"),
    # 修改文章
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    # 前台展示文章列表
    path('list-article-titles/', views.article_titles, name="article_titles"),
    # 前台展示具体文章信息
    path('article-content/<int:id>/<slug:slug>/', views.article_detail, name="article_content"),
    # 显示某一作者的全部文章信息
    path('list-article-titles/<username>/', views.article_titles, name="author_articles"),
    # 点赞文章
    path('like-article/', views.like_article, name="like_article"),
    # 文章标签
    path('article-tag/', views.article_tag, name="article_tag"),
    # 删除文章标签
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 如果不用自定义的方式指定模板位置，Django会在运行时自动去templates查找render()函数中所指定的模板文件。
    path(r'', views.blog_list, name='blog_list'),
    path(r'<int:article_id>/', views.blog_detail, name='blog_detail'),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # 进入聊天室
    path('', views.enter, name='enter'),
    # 聊天室界面，这样可以解析room_name，直接做字符串保持
    path('<str:room_name>/', views.room, name='room'),
    # 个人所有信息界面
    # path('contact/', views.contact, name='all_contact'),
    # 个人私聊界面
    path('contact/<str:user1_name>/<str:user2_name>', views.contact, name='contact'),
]

image/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'image'

urlpatterns = [
    # 图片列表
    path('list-images/', views.list_images, name="list_images"),
    # 上传图片
    path('upload-image/', views.upload_image, name='upload_image'),
    # 删除图片
    path('del-image/', views.del_image, name='del_image'),
    # 瀑布流式展示图片
    path('images/', views.falls_images, name="falls_images"),
]

myblog2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新版django取消了默认namespace，一定要加namespace，这样html文件中才可以访问blog
    # 如果加上namespace，那么include前面的第一个参数需要改为二元组，第二个内容为app_name
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),  # django自带模板
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('image/', include(('image.urls', 'image'), namespace='image')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 添加允许访问media的url

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>  <!--如果是未前后分离，这里是放入title的位置-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--<link rel="stylesheet" href="http://necolas.github.io/normalize.css/">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
</head>
<body>

{% include "header.html" %}
<div class="container">
    {% block content %} {% endblock %}
</div>

{% include "live2d.html" %}
{% include "footer.html" %}
{% block javascript %} {% endblock %}


<!--使用的css和js位置-->
<!--<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">@copy right Peter Ye</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static '/images/logo.jpg' %}" width="20px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">网站主页</a></li>
                <li><a href="{% url 'blog:blog_list' %}">博客</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                <li><a href="{% url 'chat:enter' %}">聊天室</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}  <!--如果用户已登录-->
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <!--下拉菜单-->
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>
                            {{ user.username }}<span class='caret'></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'account:edit_my_information' %}">完善信息</a></li>
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:password_reset' %}">密码重置</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                            <li><a href="#">我的私信（施工）</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">注销</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">登录</a></li>
                <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% block title %} 主页 {% endblock %}
{% block content %}
<div class="text-center">
    <h1>欢迎访问本网站！</h1>
    <h4>————人生苦短，我用python</h4>
    <h3>Web框架采用django，参考自https://www.jianshu.com/p/ce4384ea5e06</h3>
    {% load staticfiles %}
    <img src="{% static 'images/logo.jpg' %}" width="200px">
</div>
{% endblock %}

templates/live2d.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static '/live2d/css/live2d.css'%}" />

<div id="landlord">
    <div class="message" style="opacity:0"></div>
    <canvas id="live2d" width="280" height="250" class="live2d"></canvas>
    <div class="hide-button">隐藏</div>
</div>

<script type="text/javascript">
    var message_Path = "{% static '/live2d/'%}";
    var home_Path = ''  //此处修改为你的域名，必须带斜杠
</script>
<script type="text/javascript" src="{% static '/live2d/js/live2d.js'%}"></script>
<script type="text/javascript" src="{% static '/live2d/js/message.js'%}"></script>
<script type="text/javascript">
    var path = "{% static "/live2d/model/pio/"%}";
    //var model = ["pio","snow_miku","tia"];
    //extention = "model.json"
    var extention = "model"+Math.floor(Math.random()*80)+".json";  //随机取0~79的整数
    var result = path + extention;
    loadlive2d("live2d", result);
</script>

templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
            页数： {{ page.number }} / {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">下一页</a> {% endif %}
    </span>
</div>